// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuJWVqbUSTvl1te4BPRP9uKFL1qgYWTVg',
    appId: '1:1011706065434:web:279de07841dc6f79b157a3',
    messagingSenderId: '1011706065434',
    projectId: 'alenlachu-968e7',
    authDomain: 'alenlachu-968e7.firebaseapp.com',
    storageBucket: 'alenlachu-968e7.appspot.com',
    measurementId: 'G-61Z0GE1ZJT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1XHR8KKEZ8Eo7IDnOB7oHQ4muWChlVRs',
    appId: '1:1011706065434:android:13c807da8e387d6db157a3',
    messagingSenderId: '1011706065434',
    projectId: 'alenlachu-968e7',
    storageBucket: 'alenlachu-968e7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHn2_ofi2_OnSQjfZBGRAM_jxR3wp-5Po',
    appId: '1:1011706065434:ios:62d3aac4affc8882b157a3',
    messagingSenderId: '1011706065434',
    projectId: 'alenlachu-968e7',
    storageBucket: 'alenlachu-968e7.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHn2_ofi2_OnSQjfZBGRAM_jxR3wp-5Po',
    appId: '1:1011706065434:ios:62d3aac4affc8882b157a3',
    messagingSenderId: '1011706065434',
    projectId: 'alenlachu-968e7',
    storageBucket: 'alenlachu-968e7.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuJWVqbUSTvl1te4BPRP9uKFL1qgYWTVg',
    appId: '1:1011706065434:web:e1dacce2ebaf4479b157a3',
    messagingSenderId: '1011706065434',
    projectId: 'alenlachu-968e7',
    authDomain: 'alenlachu-968e7.firebaseapp.com',
    storageBucket: 'alenlachu-968e7.appspot.com',
    measurementId: 'G-6WKHD9Z070',
  );
}
